monolog:
    handlers:
        sentry:
            type: service
            id: Sentry\Monolog\Handler

sentry:
    dsn: "https://90a58854925f0d35f4456bd392ac495e@o4505753615466496.ingest.sentry.io/4505787134115840"
    options:
        error_types: "E_ALL & ~E_USER_DEPRECATED"
        capture_silenced_errors: false

services:
    _defaults:
        public: true

    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR